version: '3'
services:
    db:
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3336:3306"
        volumes: 
            - "db_data:/var/lib/mysql"
            - .\pro.sql:/docker-entrypoint-initdb.d/pro.sql
        environment: 
            MYSQL_ROOT_PASSWORD: 'asd'
volumes:
    db_data: 
 
    
            